### ISSUE TITLE
Font size too small

### ISSUE THREAD

**Issue by LeoEckert** [socialdistancingdashboard/frontendv2#12]
The font size of the buttons is too small. Its very hard to read and the buttons in the footer are very hard to interact with. 

I uploaeded a screencast showing the issue: 
https://drive.google.com/drive/folders/18sXbXBoTwZGx9vZycHc7lI0OmnygK440?usp=sharing

![Screenshot_20200924-024014](https://user-images.githubusercontent.com/66844807/94088115-ebaa6a00-fe0f-11ea-8629-5b01e72b4efa.jpg)
![Screenshot_20200924-024034](https://user-images.githubusercontent.com/66844807/94088119-ecdb9700-fe0f-11ea-98cd-3d6790b16c1c.jpg)
![Screenshot_20200924-024131](https://user-images.githubusercontent.com/66844807/94088122-ee0cc400-fe0f-11ea-979e-8cf5058c9045.jpg)

**Comment by m-ad** [comment]
Fixed by 542d4725863f562ce8d40c02997503973df8f02c
