### ISSUE TITLE
Measurement selection not working with "veranstaltungen"

### ISSUE THREAD

**Issue by BihJ** [socialdistancingdashboard/frontendv2#14]
Veranstaltungen has been implemented but the selection isnt working since then.
Points are not disappearing after unselecting a measurement. 

59333e03cfb8d78e3fde696ab201219e8e2db44e

![image](https://user-images.githubusercontent.com/42575200/94270749-daad4600-ff40-11ea-9b5b-5bc5085c886b.png)

**Comment by m-ad** [comment]
Fixed by ad4f15934dc47227ce56170dce3c3b6906ac6dac
