### ISSUE TITLE
Missing Link to supportive initatives

### ISSUE THREAD

**Issue by LeoEckert** [socialdistancingdashboard/frontendv2#4]
For better transparany supportive initatives as the solution enabler should be linked. This is working on the main page if you open "Informationen anzeigen". However it does not work on the blog. 
![Bildschirmfoto von 2020-09-24 02-01-06](https://user-images.githubusercontent.com/66844807/94085959-daf6f580-fe09-11ea-92a3-f9400d30cd4e.png)

**Comment by m-ad** [comment]
This is not a dash frontend issue but related to the wordpress blog. Anyway, it's fixed now.
