### ISSUE TITLE
"i" button has no fuction

### ISSUE THREAD

**Issue by LeoEckert** [socialdistancingdashboard/frontendv2#5]
The button on the bottom right corner has no function
![Screenshot (91)](https://user-images.githubusercontent.com/66844807/94088463-da159200-fe10-11ea-9696-509093e59c3d.png)

**Comment by m-ad** [comment]
That's the source info button for the basemap. It was blocked by the transparent footer container above it. Fixed in 81dd71ccd9d4b2533dbb1d6e8a48e2e2a0df91d1.
