### ISSUE TITLE
Screen recorder works not acurate

### ISSUE THREAD

**Issue by LeoEckert** [socialdistancingdashboard/frontendv2#6]
The frontend has the fuction to save the current map into an image file. This function does not work acurate.

I have documented this issue two times with two different examples: 
![Screenshot1](https://user-images.githubusercontent.com/66844807/94086533-8fdde200-fe0b-11ea-8769-91f591e458be.png)
![Download1](https://user-images.githubusercontent.com/66844807/94086537-910f0f00-fe0b-11ea-880a-f3ec013bea6c.png)
![Download2](https://user-images.githubusercontent.com/66844807/94086541-92403c00-fe0b-11ea-99a0-12dd054b3000.png)
![Screenshot2](https://user-images.githubusercontent.com/66844807/94086544-93716900-fe0b-11ea-85f0-73cf3a1906f5.png)

**Comment by m-ad** [comment]
Removed that broken functionality for the map in d921e5e08ee435760d0471a9bb45cd35efa416d4 because it did not work as expected.
