### ISSUE TITLE
Missing certificate for some pages

### ISSUE THREAD

**Issue by LeoEckert** [socialdistancingdashboard/frontendv2#7]
The page appears not trust worthy if there are pages with a missing certificate.
![Screenshot (92)](https://user-images.githubusercontent.com/66844807/94086790-480b8a80-fe0c-11ea-8826-585b69438c0d.png)

**Comment by m-ad** [comment]
This is not a problem with the Dash frontend, it's related to the Wordpress blog (wordpress uses http for images instead of https when added in the editor. Can be fixed by manually changing the each image source to https).
