### ISSUE TITLE
Untrustworthy graph

### ISSUE THREAD

**Issue by LeoEckert** [socialdistancingdashboard/frontendv2#9]
The agreation based on serveral sometimes one datapoints to a country district (Bundesland) is not acurate and makes the  page a lot untrustworthy. 
![Bildschirmfoto von 2020-09-01 02-45-29 (1)](https://user-images.githubusercontent.com/66844807/94087435-0aa7fc80-fe0e-11ea-94e9-022d8e0e1538.png)
![Bildschirmfoto von 2020-09-01 02-45-15 (1)](https://user-images.githubusercontent.com/66844807/94087437-0bd92980-fe0e-11ea-9fee-ebda8e3a1a04.png)

**Comment by m-ad** [comment]
Bundesland aggregation will be removed, see #19
